[package]
name = "k256"
version = "0.14.0-pre.9"
description = """
secp256k1 elliptic curve library written in pure Rust with support for ECDSA
signing/verification/public-key recovery, Taproot Schnorr signatures (BIP340),
Elliptic Curve Diffie-Hellman (ECDH), and general-purpose secp256k1 elliptic
curve group operations which can be used to implement arbitrary protocols
"""
authors = ["RustCrypto Developers"]
license = "Apache-2.0 OR MIT"
documentation = "https://docs.rs/k256"
homepage = "https://github.com/RustCrypto/elliptic-curves/tree/master/k256"
repository = "https://github.com/RustCrypto/elliptic-curves"
readme = "README.md"
categories = ["cryptography", "cryptography::cryptocurrencies", "no-std"]
keywords = ["bitcoin", "crypto", "ecc", "ethereum", "secp256k1"]
edition = "2024"
rust-version = "1.85"

[dependencies]
cfg-if = "1.0"
elliptic-curve = { version = "0.14.0-rc.10", default-features = false, features = ["sec1"] }
hash2curve = { version = "0.14.0-rc.0", optional = true }

# optional dependencies
once_cell = { version = "1.21", optional = true, default-features = false }
ecdsa-core = { version = "0.17.0-rc.4", package = "ecdsa", optional = true, default-features = false, features = ["der"] }
hex-literal = { version = "1", optional = true }
serdect = { version = "0.3", optional = true, default-features = false }
sha2 = { version = "0.11.0-rc.0", optional = true, default-features = false }
signature = { version = "3.0.0-rc.1", optional = true }
powdr-openvm-hints-guest = { git = "https://github.com/powdr-labs/powdr.git" }

openvm = { git = "https://github.com/powdr-labs/openvm.git", optional = true }

[target.'cfg(target_os = "zkvm")'.dependencies]
openvm = { git = "https://github.com/powdr-labs/openvm.git" }

[dev-dependencies]
blobby = "0.3"
criterion = "0.7"
ecdsa-core = { version = "0.17.0-rc.4", package = "ecdsa", default-features = false, features = ["dev"] }
hex = "0.4.3"
hex-literal = "1"
num-bigint = "0.4"
num-traits = "0.2"
proptest = "1.7"
rand_core = { version = "0.9", features = ["os_rng"] }
sha3 = { version = "0.11.0-rc.0", default-features = false }

[features]
default = ["arithmetic", "ecdsa", "pkcs8", "precomputed-tables", "schnorr", "std","expose-field"]
alloc = ["ecdsa-core?/alloc", "elliptic-curve/alloc"]
std = ["alloc", "ecdsa-core?/std", "elliptic-curve/std", "once_cell?/std"]

arithmetic = ["elliptic-curve/arithmetic"]
bits = ["arithmetic", "elliptic-curve/bits"]
critical-section = ["once_cell/critical-section", "precomputed-tables"]
digest = ["ecdsa-core/digest", "ecdsa-core/hazmat"]
ecdh = ["arithmetic", "elliptic-curve/ecdh"]
ecdsa = ["arithmetic", "ecdsa-core/signing", "ecdsa-core/verifying", "sha256"]
expose-field = ["arithmetic"]
hash2curve = ["arithmetic", "dep:hash2curve"]
jwk = ["elliptic-curve/jwk"]
pem = ["ecdsa-core/pem", "elliptic-curve/pem", "pkcs8"]
pkcs8 = ["ecdsa-core/pkcs8", "elliptic-curve/pkcs8"]
precomputed-tables = ["arithmetic"]
schnorr = ["arithmetic", "sha256", "signature"]
serde = ["ecdsa-core/serde", "elliptic-curve/serde", "pkcs8", "serdect"]
sha256 = ["digest", "sha2"]
test-vectors = ["hex-literal"]

[package.metadata.docs.rs]
features = ["ecdh", "ecdsa", "schnorr"]
rustdoc-args = ["--cfg", "docsrs"]

[[bench]]
name = "ecdsa"
harness = false
required-features = ["ecdsa", "sha256"]

[[bench]]
name = "field"
harness = false
required-features = ["expose-field"]

[[bench]]
name = "scalar"
harness = false
