[workspace]
resolver = "2"
members = [
    "bign256",
    "bp256",
    "bp384",
    "k256",
    "p192",
    "p224",
    "p256",
    "p384",
    "p521",
    "primefield",
    "primeorder",
    "sm2"
]

[profile.dev]
opt-level = 2

[patch.crates-io]
# https://github.com/zkcrypto/ff/pull/122
ff = { git = "https://github.com/pinkforest/ff.git", branch = "bump-rand-core" }

# https://github.com/zkcrypto/group/pull/56
group = { git = "https://github.com/pinkforest/group.git", branch = "bump-rand-0.9" }

# https://github.com/RustCrypto/signatures/pull/913
ecdsa = { git = "https://github.com/RustCrypto/signatures.git" }

elliptic-curve = { git = "https://github.com/RustCrypto/traits.git" }
signature      = { git = "https://github.com/RustCrypto/traits.git" }
