[workspace]
resolver = "2"
members = [
    "bign256",
    "bp256",
    "bp384",
    "ed448-goldilocks",
    "k256",
    "p192",
    "p224",
    "p256",
    "p384",
    "p521",
    "primefield",
    "primeorder",
    "sm2"
]

[profile.dev]
opt-level = 2
