[package]
name = "p256"
description = "NIST P-256 elliptic curve"
version = "0.2.0"
authors = ["RustCrypto Developers"]
license = "Apache-2.0 OR MIT"
documentation = "https://docs.rs/elliptic-curve"
repository = "https://github.com/RustCrypto/elliptic-curves/tree/master/p256"
readme = "README.md"
edition = "2018"
categories = ["cryptography", "no-std"]
keywords = ["crypto", "ecc", "nist"]

[dependencies.elliptic-curve]
version = "0.3"
path = "../elliptic-curve-crate"
default-features = false
features = ["weierstrass"]

[dependencies.subtle]
version = "2.2.2"
optional = true
default-features = false

[dev-dependencies]
hex = "0.4"
proptest = "0.9"

[features]
default = ["arithmetic", "std"]
arithmetic = ["subtle"]
test-vectors = []
std = ["elliptic-curve/std"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
