[package]
name = "bp384"
version = "0.6.0"
description = "Brainpool P-384 (brainpoolP384r1 and brainpoolP384t1) elliptic curves"
authors = ["RustCrypto Developers"]
license = "Apache-2.0 OR MIT"
documentation = "https://docs.rs/bp384"
repository = "https://github.com/RustCrypto/elliptic-curves/tree/master/bp384"
readme = "README.md"
categories = ["cryptography", "no-std"]
keywords = ["brainpool", "crypto", "ecc"]
edition = "2021"
rust-version = "1.65"

[dependencies]
elliptic-curve = { version = "0.13", default-features = false, features = ["hazmat", "sec1"] }

# optional dependencies
ecdsa = { version = "0.16", optional = true, default-features = false, features = ["der"] }
primeorder = { version = "0.13.1", optional = true, path = "../primeorder" }
sha2 = { version = "0.10", optional = true, default-features = false }

[features]
default = ["pkcs8", "std"]
alloc = ["ecdsa?/alloc", "elliptic-curve/alloc"]
std = ["alloc", "ecdsa?/std", "elliptic-curve/std"]

arithmetic = ["dep:primeorder"]
pem = ["elliptic-curve/pem", "pkcs8"]
pkcs8 = ["ecdsa/pkcs8", "elliptic-curve/pkcs8"]
serde = ["ecdsa/serde", "elliptic-curve/serde", "primeorder?/serde"]
sha384 = ["ecdsa/digest", "ecdsa/hazmat", "sha2"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
