[package]
name = "bp384"
description = "Brainpool P-384 (brainpoolP384r1 and brainpoolP384t1) elliptic curves"
version = "0.2.0-pre" # Also update html_root_url in lib.rs when bumping this
authors = ["RustCrypto Developers"]
license = "Apache-2.0 OR MIT"
documentation = "https://docs.rs/elliptic-curve"
repository = "https://github.com/RustCrypto/elliptic-curves/tree/master/bp384"
readme = "README.md"
edition = "2018"
categories = ["cryptography", "no-std"]
keywords = ["brainpool", "crypto", "ecc"]

[dependencies]
ecdsa = { version = "=0.12.0-pre", optional = true, default-features = false, features = ["der"] }
elliptic-curve = { version = "0.10.0-pre", default-features = false, features = ["hazmat"] }
sha2 = { version = "0.9", optional = true, default-features = false }

[features]
default = ["pkcs8", "std"]
pem = ["elliptic-curve/pem", "pkcs8"]
pkcs8 = ["elliptic-curve/pkcs8", "zeroize"]
sha384 = ["ecdsa/digest", "ecdsa/hazmat", "sha2"]
std = ["elliptic-curve/std"]
zeroize = ["elliptic-curve/zeroize"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
